var apropos = "AGAT est né d'un constat simple : la multiplication des outils numériques de cartographie proposés aux collectivités, souvent complexes, ne parviennent pas toujours à combler les réels besoins métiers de leurs utilisateurs.<br>Combien de SIG, très coûteux, mis en place, et que personne ne sait utiliser en mairie ?<br>Face à ce qui reste un énorme besoin en matière de solutions de gestion de l’information géographique, le cabinet AGAT se positionne comme un acteur privilégié auprès des gestionnaires de territoires : partant de l'évaluation précise de leurs besoins avec une approche métier, les solutions AGAT sont adaptées aux différents acteurs locaux.";
var auditTxt = "Nous vous accompagnons pour la gestion optimisée de vos données géolocalisées à l'échelle de votre structure";
var urbaTxt = "Dématérialisation de vos PLU(i) ou autres documents d'urbanisme, au format SIG respectant la norme INSPIRE, et téléversement sur le Géoportail de l'Urbanisme<br><br><a href='http://www.conformite-geoportail-urbanisme.fr/' target='_blank'>http://www.conformite-geoportail-urbanisme.fr/</a>";
var formaTxt = "Formations QGIS métier : des programmes sur-mesure thématiques pour les ingénieurs territoriaux, bureaux d'études, services techniques<br>Des supports et programmes personnalisés adaptés à votre thématique métier<br>Des formateurs déclarés avec une expérience reconnue depuis plusieurs années : nous sommes intervenus pour l'INAO, IdeoBFC, le PNR du Haut-Jura, la chambre d'agriculture de la Côte d'Or, des bureaux d'études privés...<br>Exercices intéressants et nombreux" "Convivialité et bonne ambiance" "Qualité des données et des otuils utilisés" 
var integrTxt = "Enrichissez votre SIG en intégrant les données métier de votre quotidien";
var portailTxt = "Mettez en valeur votre territoire et vos données avec un portail web cartographique original et personnalisé<br>Les principales fonctionnalités d'un SIG pour les non-géomaticiens";
var reglemTxt = "Confiez-nous la numérisation de vos réseaux et leur téléversement sur le portail de l'INERIS <a href='http://www.carto-reseaux.fr' target='_blank'>http://www.carto-reseaux.fr</a>;<br>Partenariat national carto-réseaux : nous intervenons partout en France via nos différents partenaires pour prendre en charge de A à Z la numérisation de vos réseaux." 


//revenir à la ligne: <br>
//insérer image: <img src="img/xxxx.png"> en mettant l'image dans le dossier img/
